export const FETCH_TEAM_MATCH_REQUEST = "FETCH_TEAM_MATCH_REQUEST";
export const FETCH_TEAM_MATCH_SUCCESS = "FETCH_TEAM_MATCH_SUCCESS";
export const FETCH_TEAM_MATCH_ERROR = "FETCH_TEAM_MATCH_ERROR";
